// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOLLSuojMpedv8wm1-Bl_elb-2YVCWfDo',
    appId: '1:654772187209:web:0ea38fc749019124638f98',
    messagingSenderId: '654772187209',
    projectId: 'grouplist-5ecc8',
    authDomain: 'grouplist-5ecc8.firebaseapp.com',
    storageBucket: 'grouplist-5ecc8.firebasestorage.app',
    measurementId: 'G-ZSV17Z0Q8L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9i6rvxHCx7gpJVcwUAlk0ps6DNCrr63c',
    appId: '1:654772187209:android:739f2cbe584136de638f98',
    messagingSenderId: '654772187209',
    projectId: 'grouplist-5ecc8',
    storageBucket: 'grouplist-5ecc8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRgQaop3UlfKLYVPDJIDiDTaFnH6cNvns',
    appId: '1:654772187209:ios:e4808d4c2175e071638f98',
    messagingSenderId: '654772187209',
    projectId: 'grouplist-5ecc8',
    storageBucket: 'grouplist-5ecc8.firebasestorage.app',
    iosBundleId: 'com.example.grouplist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRgQaop3UlfKLYVPDJIDiDTaFnH6cNvns',
    appId: '1:654772187209:ios:e4808d4c2175e071638f98',
    messagingSenderId: '654772187209',
    projectId: 'grouplist-5ecc8',
    storageBucket: 'grouplist-5ecc8.firebasestorage.app',
    iosBundleId: 'com.example.grouplist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOLLSuojMpedv8wm1-Bl_elb-2YVCWfDo',
    appId: '1:654772187209:web:e7c84ec6408e4a26638f98',
    messagingSenderId: '654772187209',
    projectId: 'grouplist-5ecc8',
    authDomain: 'grouplist-5ecc8.firebaseapp.com',
    storageBucket: 'grouplist-5ecc8.firebasestorage.app',
    measurementId: 'G-7J5EPYQG7C',
  );
}
